app/project/account_module/urls.py
from django.urls import path
from . import views


app_name='account_module'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user-register'),    
    path('login/',views.UserLoginView.as_view(),name='user-login'),    
    path('forget-password/',views.UserForgetPasswordView.as_view(),name='user-forget-password'),    
    path('change-password/',views.UserChangePasswordView.as_view(),name='user-change-password'),    
    path('otp-code/',views.UserOtpCode.as_view(),name='user-otp-code'),    
    path('logout/',views.UserLogOutView.as_view(),name='user-logout'),    
]

app/project/blog_module/urls.py
from django.urls import path,re_path
from . import views


app_name='blog_module'
urlpatterns = [
    path('',views.ArticleListView.as_view(),name="articles"),
    # article comment
    path('add-comment/article_comment/',views.add_article_comment,name='add-article-comment'),
    # article detail
    path('<int:pk>/<slug:slug>/',views.ArticleDetailView.as_view(),name="article-detail"),
    re_path(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/\Z$', views.ArticleDetailView.as_view(), name='article-detail'),
]

app/project/contact_module/urls.py
from django.urls import path
from . import views


app_name='contact_module'
urlpatterns = [
    path('contact-us/',views.ContactUsView.as_view(),name="contact-us"),
    path('test-map/',views.test_map,name="test-map"),
]

app/project/ghanbari_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_module.urls',namespace='home_module')),
    path('account/',include('account_module.urls',namespace='account_module')),
    path('contact-us/',include('contact_module.urls',namespace='contact_module')),
    path('about-us/',include('about_us_module.urls',namespace='about_us_module')),
    path('products/',include('product_module.urls',namespace='product_module')),
    path('orders/',include('order_module.urls',namespace='order_module')),
    path('blog/',include('blog_module.urls',namespace='blog_module')),
    path('profile/',include('user_profile_module.urls',namespace='user_profile_module')),
    path('ckeditor5/', include('django_ckeditor_5.urls')), 
    path('zarinpal/', include('zarinpal_module.urls',namespace='zarinpal_module')), 
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

app/project/home_module/urls.py
from django.urls import path
from . import views


app_name='home_module'
urlpatterns = [
    path('',views.homePageView.as_view(),name='home-page'),
    path('footer_component/',views.FooterEmailSubmitView.as_view(),name='footer-component'),

]

app/project/product_module/urls.py
from django.urls import path,re_path
from . import views


app_name="product_module"
urlpatterns = [
    # products 
    path('',views.ProductListView.as_view(),name='products'),
    # product detail
    path('<int:pk>/<slug:slug>/',views.ProductDetailView.as_view(),name='product-detail'),
    re_path(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/\Z$', views.ProductDetailView.as_view(), name='product-detail'),
    # add product to user fav list
    path('add-to-user-favorite-list/',views.add_remove_product_to_favorite_list,name='add-product-to-favorite-list'),
    path('add-product-comment/',views.add_product_comment,name="add-product-comment")
]

app/project/templates/base.html
{% load render_partial %}

<!DOCTYPE html>
<html lang="fa">
    <head>
        {% include "includes/header_links.html" %}
        {% block header_references %}{% endblock header_references %}
    </head>
    <body class="shop-main-h">
        <!-- rts header area start -->
        <!-- rts header area start -->
        <div class="rts-header-one-area-one">
            {% render_partial 'home_module.views.header_component' %}
        </div>
        <!-- rts header area end -->

        <!-- rts header area start -->
        <!-- header style two -->
        <div id="side-bar" class="side-bar header-two">
            {% render_partial 'home_module.views.mobile_sidebar_component' %}
        </div>
        <!-- header style two End -->
        <!-- rts header area end -->
        <!-- rts header area end -->

        {% include "includes/messages.html" %}

        {% block content %}

        {% endblock content %}
        
        {% include "includes/services.html" %}
        
        <!-- rts footer one area start -->
        <div class="rts-footer-area pt--80 bg_light-1">
            {% render_partial "home_module.views.FooterComponent" %}
        </div>
        <!-- rts footer one area end -->

        <!-- rts copyright-area start -->
        <div class="rts-copyright-area">
            {% render_partial "home_module.views.copyright_component" %}
        </div>
        <!-- rts copyright-area end -->

        <!-- modal -->
        <!-- this is first pop up when page load-->
        {% comment %}
            <div id="myModal-1" class="modal fade" role="dialog">
                <div class="modal-dialog bg_image">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-bs-dismiss="modal"><i class="fa-light fa-x"></i></button>
                        </div>
                        <div class="modal-body text-center">
                            <div class="inner-content">
                                <div class="content">
                                    <span class="pre-title">در اولین خرید 150 تومانی خود تا 30 درصد تخفیف دریافت کنید</span>
                                    <h1 class="title">
                                        خانواده خود را با <br />
                                        بهترین قیمت تغذیه کنید
                                    </h1>
                                    <p class="disc">
                                        ما برای شما تخفیفات ویژه ای را در مورد محصولات غذایی آماده کرده ایم. این فرصت ها را از دست ندهید <br />
                                        ...
                                    </p>
                                    <div class="rts-btn-banner-area">
                                        <a href="#" class="rts-btn btn-primary radious-sm with-icon">
                                            <div class="btn-text">
                                                اکنون فروشگاه
                                            </div>
                                            <div class="arrow-icon">
                                                <i class="fa-light fa-arrow-left"></i>
                                            </div>
                                            <div class="arrow-icon">
                                                <i class="fa-light fa-arrow-left"></i>
                                            </div>
                                        </a>
                                        <div class="price-area">
                                            <span>از</span>
                                            <h3 class="title animated fadeIn">80.99 تومان</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        {% endcomment %}
        <!-- end modal -->

        <!--================= Preloader Section Start Here =================-->
        <div id="weiboo-load">
            <div class="preloader-new">
                <svg class="cart_preloader" role="img" aria-label="انیمیشن خط سبد خرید_preloader" viewBox="0 0 128 128" width="128px" height="128px" xmlns="http://www.w3.org/2000/svg">
                    <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="8">
                        <g class="cart__track" stroke="hsla(0,10%,10%,0.1)">
                            <polyline points="4,4 21,4 26,22 124,22 112,64 35,64 39,80 106,80"></polyline>
                            <circle cx="43" cy="111" r="13"></circle>
                            <circle cx="102" cy="111" r="13"></circle>
                        </g>
                        <g class="cart__lines" stroke="currentColor">
                            <polyline class="cart__top" points="4,4 21,4 26,22 124,22 112,64 35,64 39,80 106,80" stroke-dasharray="338 338" stroke-dashoffset="-338"></polyline>
                            <g class="cart__wheel1" transform="rotate(-90,43,111)">
                                <circle class="cart__wheel-stroke" cx="43" cy="111" r="13" stroke-dasharray="81.68 81.68" stroke-dashoffset="81.68"></circle>
                            </g>
                            <g class="cart__wheel2" transform="rotate(90,102,111)">
                                <circle class="cart__wheel-stroke" cx="102" cy="111" r="13" stroke-dasharray="81.68 81.68" stroke-dashoffset="81.68"></circle>
                            </g>
                        </g>
                    </g>
                </svg>
            </div>
        </div>
        <!--================= Preloader End Here =================-->

        <!--mobile search form-->
        <form action="{% url "product_module:products" %}" class="search-header" novalidate> 
            <div class="search-input-area">
                <div class="container">
                    <div class="search-input-inner">
                        <div class="input-div">
                                <input type="text" name="product-search" placeholder=" دنبال چه محصولی هستی؟" />
                                <button><i class="far fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                <div id="close" class="search-close-icon"><i class="far fa-times"></i></div>
            </div>
        </form>
        <!--end mobile search form-->
        
        <div id="anywhere-home" class="anywere"></div>
        
        <!-- progress area start -->
        <div class="progress-wrap">
            <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
                <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" style="transition: stroke-dashoffset 10ms linear 0s; stroke-dasharray: 307.919, 307.919; stroke-dashoffset: 307.919;"></path>
            </svg>
        </div>
        <!-- progress area end -->

        {% include "includes/footer_links.html" %}
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                let cartIcon = document.querySelector(".fa-cart-shopping");
                if (cartIcon) {
                    let basketCount = cartIcon.getAttribute("data-basket-count") || "0";
                    cartIcon.style.setProperty("--basket-count", `"${basketCount}"`);
                }
            });
        </script>
        
        {% block footer_references %}{% endblock footer_references %}
    </body>
</html>

app/project/templates/copyright_component.html
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="copyright-between-1">
                <p class="disc">تمامی محتویات این سایت متعلق به <a href="#">@خوشه </a>.می باشد.حق انتشار محفوظ است </p>
                {% comment %} <a href="#" class="playstore-app-area">
                    <span>دانلود برنامه</span>
                    <img src="/static/assets/images/payment/02.png" alt="" />
                    <img src="/static/assets/images/payment/03.png" alt="" />
                </a> {% endcomment %}
            </div>
        </div>
    </div>
</div>

app/project/templates/mobile_sidebar_component.html
<button class="close-icon-menu"><i class="far fa-times"></i></button>

<form action="{% url "product_module:products" %}" class="search-input-area-menu mt--30" novalidate >
    <input type="text" name="product-search" placeholder=" جستجو" />
    <button><i class="fa-light fa-magnifying-glass"></i></button>
</form>

<div class="mobile-menu-nav-area tab-nav-btn mt--20">
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">منو</button>
            {% comment %} <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">دسته بندی</button> {% endcomment %}
        </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
            <!-- mobile menu area start -->
            <div class="mobile-menu-main">
                <nav class="nav-main mainmenu-nav mt--30">
                    <ul class="mainmenu metismenu" id="mobile-menu-active">
                        <li>
                            <a href="{% url "home_module:home-page" %}" class="main">صفحه اصلی</a>
                        </li>
                        <li>
                            <a href="{% url "about_us_module:about-us" %}" class="main">درباره ما</a>
                        </li>
                        <li>
                            <a href="{% url "contact_module:contact-us" %}" class="main">تماس با ما</a>
                        </li>
                        <li>
                            <a href="{% url "blog_module:articles" %}" class="main">مقالات</a>
                        </li>
                        {% if request.user.is_authenticated and request.user.is_superuser %}
                            <li>
                                <a href="/admin" class="main">ادمین</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <!-- mobile menu area end -->
        </div>
        {% comment %} <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
            <div class="category-btn category-hover-header menu-category">
                <ul class="category-sub-menu" id="category-active-menu">
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/01.svg" alt="نمادها" />
                            <span>صبحانه و لبنیات</span>
                            <i class="fa-regular fa-plus"></i>
                        </a>
                        <ul class="submenu mm-collapse">
                            <li><a class="mobile-menu-link" href="#">صبحانه</a></li>
                            <li><a class="mobile-menu-link" href="#">شام</a></li>
                            <li><a class="mobile-menu-link" href="#">پمپ کردن</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/02.svg" alt="نمادها" />
                            <span>گوشت و غذاهای دریایی</span>
                            <i class="fa-regular fa-plus"></i>
                        </a>
                        <ul class="submenu mm-collapse">
                            <li><a class="mobile-menu-link" href="#">صبحانه</a></li>
                            <li><a class="mobile-menu-link" href="#">شام</a></li>
                            <li><a class="mobile-menu-link" href="#">پمپ کردن</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/03.svg" alt="نمادها" />
                            <span>نان و نانوایی</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/04.svg" alt="نمادها" />
                            <span>چیپس و اسنک</span>
                            <i class="fa-regular fa-plus"></i>
                        </a>
                        <ul class="submenu mm-collapse">
                            <li><a class="mobile-menu-link" href="#">صبحانه</a></li>
                            <li><a class="mobile-menu-link" href="#">شام</a></li>
                            <li><a class="mobile-menu-link" href="#">پمپ کردن</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/05.svg" alt="نمادها" />
                            <span>مراقبت های پزشکی</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/06.svg" alt="نمادها" />
                            <span>نان و نانوایی</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/07.svg" alt="نمادها" />
                            <span>بیسکویت و تنقلات</span>
                            <i class="fa-regular fa-plus"></i>
                        </a>
                        <ul class="submenu mm-collapse">
                            <li><a class="mobile-menu-link" href="#">صبحانه</a></li>
                            <li><a class="mobile-menu-link" href="#">شام</a></li>
                            <li><a class="mobile-menu-link" href="#">پمپ کردن</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/08.svg" alt="نمادها" />
                            <span>غذای یخ زده</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/09.svg" alt="نمادها" />
                            <span>مواد غذایی و منگنه</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu-item">
                            <img src="/static/assets/images/icons/10.svg" alt="نمادها" />
                            <span>سایر موارد</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div> {% endcomment %}
    </div>
</div>

<!-- button area wrapper start -->
<div class="button-area-main-wrapper-menuy-sidebar mt--50">
    <div class="contact-area">
        {% if site_setting.phone %}
            <div class="phone">
                <i class="fa-light fa-headset"></i>
                <a href="">{{site_setting.phone}}</a>
            </div>
        {% endif %}
        {% if site_setting.email %}
        <div class="phone">
            <i class="fa-light fa-envelope"></i>
            <a href="">{{site_setting.email}}</a>
        </div>
        {% endif %}

    </div>
    <div class="buton-area-bottom">
        {% if request.user.is_authenticated %}
            <a href="{% url "account_module:user-logout" %}" class="rts-btn btn-primary">خروج</a>
        {% else %}
            <a href="{% url "account_module:user-register" %}" class="rts-btn btn-primary">ثبت نام</a>
            <a href="{% url "account_module:user-login" %}" class="rts-btn btn-primary">ورود</a>
        {% endif %}
    </div>
</div>
<!-- button area wrapper end -->

app/project/templates/navbar_component.html
<nav>
    <ul class="parent-nav">
        <li>
            <a href="{% url "home_module:home-page" %}">صفحه اصلی</a>
        </li>
        <li>
            <a href="{% url "about_us_module:about-us" %}">درباره ما</a>
        </li>
        <li>
            <a href="{% url "contact_module:contact-us" %}">تماس با ما</a>
        </li>
        <li>
            <a href="{% url "product_module:products" %}">محصولات</a>
        </li>
        <li>
            <a href="{% url "blog_module:articles" %}">مقالات</a>
        </li>
        {% if request.user.is_superuser %}
            <li>
                <a href="/admin">ادمین</a>
            </li>
        {% endif %}
        {% comment %} <li>
            <a href="{% url "product_module:products-two" %}">محصولات2</a>
        </li> {% endcomment %}
        {% if request.user.is_authenticated %}
        <li>
            <a href="{% url "account_module:user-logout" %}">خروج</a>
        </li>
        {% else %}
        <li>
            <a href="{% url "account_module:user-register" %}">ثبت نام</a>
        </li>
        <li>
            <a href="{% url "account_module:user-login" %}">ورود</a>
        </li>
        {% endif %}

        {% comment %} <li class="parent has-dropdown">
            <a class="nav-link" href="#">صفحه اصلی</a>
            <ul class="submenu">
                <li><a class="sub-b" href="index.html">صفحه اصلی یک</a></li>
                <li><a class="sub-b" href="index-two.html">صفحه اصلي دو</a></li>
                <li><a class="sub-b" href="index-three.html">صفحه اصلی سه</a></li>
                <li><a class="sub-b" href="index-four.html">صفحه اصلی چهار</a></li>
                <li><a class="sub-b" href="index-five.html">صفحه اصلی پنج</a></li>
            </ul>
        </li>
        <li class="parent"><a href="about.html">درباره</a></li>
        <li class="parent with-megamenu">
            <a href="#">فروشگاه</a>
            <div class="rts-megamenu">
                <div class="wrapper">
                    <div class="row align-items-center">
                        <div class="col-lg-8">
                            <div class="megamenu-item-wrapper">
                                <!-- single item areas start -->
                                <div class="single-megamenu-wrapper">
                                    <p class="title">چیدمان فروشگاه</p>
                                    <ul>
                                        <li><a href="shop-grid-sidebar.html">فروشگاه گريد سايدبار</a></li>
                                        <li><a href="shop-list-sidebar.html">فروشگاه ليست سايدبار</a></li>
                                        <li><a href="shop-grid-top-filter.html">فروشگاه گريد فيلتر بالا</a></li>
                                        <li><a href="shop-list-top-filter.html">فروشگاه ليست فيلتر بالا</a></li>
                                    </ul>
                                </div>
                                <!-- single item areas end -->
                                <!-- single item areas start -->
                                <div class="single-megamenu-wrapper">
                                    <p class="title">جزئیات فروشگاه</p>
                                    <ul>
                                        <li><a class="sub-b" href="shop-details.html">جزئیات فروشگاه</a></li>
                                        <li><a class="sub-b" href="shop-details-2.html">جزئیات فروشگاه V2</a></li>
                                        <li><a class="sub-b" href="shop-details-left-sidebar.html">جزئیات فروشگاه V3</a></li>
                                        <li><a class="sub-b" href="shop-details-4.html">جزئیات فروشگاه V4</a></li>
                                    </ul>
                                </div>
                                <!-- single item areas end -->
                                <!-- single item areas start -->
                                <div class="single-megamenu-wrapper">
                                    <p class="title">مشخصات محصول</p>
                                    <ul>
                                        <li><a class="sub-b" href="shop-details-variable.html">محصول متغیر</a></li>
                                        <li><a class="sub-b" href="shop-details-affiliats.html">محصول وابسته</a></li>
                                        <li><a class="sub-b" href="shop-details-group.html">گروه جزئیات فروشگاه</a></li>
                                        <li><a class="sub-b" href="shop-compare.html">مقايسه محصول</a></li>
                                    </ul>
                                </div>
                                <!-- single item areas end -->
                                <!-- single item areas start -->
                                <div class="single-megamenu-wrapper">
                                    <p class="title">خرید دیگران</p>
                                    <ul>
                                        <li><a class="sub-b" href="cart.html">سبد خرید</a></li>
                                        <li><a class="sub-b" href="checkout.html">صورتحساب</a></li>
                                        <li><a class="sub-b" href="trackorder.html">پیگیری سفارش</a></li>
                                    </ul>
                                </div>
                                <!-- single item areas end -->
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <a href="shop-grid-sidebar.html" class="feature-add-megamenu-area">
                                <img src="/static/assets//images/feature/05.jpg" alt="ویژگی_محصول">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <li class="parent has-dropdown">
            <a class="nav-link" href="#">فروشندگان</a>
            <ul class="submenu">
                <li><a class="sub-b" href="vendor-list.html">فروشنده ليست</a></li>
                <li><a class="sub-b" href="vendor-grid.html">فروشنده گريد</a></li>
                <li><a class="sub-b" href="vendor-details.html">جزئیات فروشنده</a></li>
            </ul>
        </li>
        <li class="parent has-dropdown">
            <a class="nav-link" href="#">صفحات</a>
            <ul class="submenu">
                <li><a class="sub-b" href="about.html">درباره</a></li>
                <li><a class="sub-b" href="store.html">فروشگاه</a></li>
                <li><a class="sub-b" href="faq.html">سوالات متداول</a></li>
                <li><a class="sub-b" href="invoice.html">صورتحساب</a></li>
                <li><a class="sub-b" href="contact.html">تماس</a></li>
                <li><a class="sub-b" href="register.html">ثبت نام</a></li>
                <li><a class="sub-b" href="login.html">وارد شدن</a></li>
                <li><a class="sub-b" href="privacy-policy.html">سیاست حفظ حریم خصوصی</a></li>
                <li><a class="sub-b" href="cookies-policy.html">خط مشی کوکی ها</a></li>
                <li><a class="sub-b" href="terms-condition.html">شرایط و ضوابط</a></li>
                <li><a class="sub-b" href="404.html">خطا</a></li>
            </ul>
        </li>
        <li class="parent has-dropdown">
            <a class="nav-link" href="#">وبلاگ</a>
            <ul class="submenu">
                <li><a class="sub-b" href="blog.html">وبلاگ</a></li>
                <li><a class="sub-b" href="blog-list-right-sidebar.html">وبلاگ سايدبار راست</a></li>
                <li><a class="sub-b" href="blog-list-left-sidebar.html">وبلاگ سايدبار چپ</a></li>
                <li><a class="sub-b" href="blog-details.html">جزئیات وبلاگ</a></li>
            </ul>
        </li>
        <li class="parent">
            <a href="contact.html">تماس</a>
        </li> {% endcomment %}
    </ul>
</nav>