app/project/blog_module/urls.py
from django.urls import path,re_path
from . import views


app_name='blog_module'
urlpatterns = [
    path('',views.ArticleListView.as_view(),name="articles"),
    # article comment
    path('add-comment/article_comment/',views.add_article_comment,name='add-article-comment'),
    # article detail
    path('<int:pk>/<slug:slug>/',views.ArticleDetailView.as_view(),name="article-detail"),
    re_path(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/\Z$', views.ArticleDetailView.as_view(), name='article-detail'),
]

app/project/ghanbari_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_module.urls',namespace='home_module')),
    path('account/',include('account_module.urls',namespace='account_module')),
    path('contact-us/',include('contact_module.urls',namespace='contact_module')),
    path('about-us/',include('about_us_module.urls',namespace='about_us_module')),
    path('products/',include('product_module.urls',namespace='product_module')),
    path('orders/',include('order_module.urls',namespace='order_module')),
    path('blog/',include('blog_module.urls',namespace='blog_module')),
    path('profile/',include('user_profile_module.urls',namespace='user_profile_module')),
    path('ckeditor5/', include('django_ckeditor_5.urls')), 
    path('zarinpal/', include('zarinpal_module.urls',namespace='zarinpal_module')), 
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

app/project/order_module/urls.py
from django.urls import path
from . import views


app_name="order_module"
urlpatterns = [
    path('add-product-to-basket-orders/',views.add_product_to_basket,name='add-product-to-basket'),
    path('basket/',views.UserOrderBasket.as_view(),name='order-basket'),
    # path('remove_order_detail/',views.remove_order_detail_user_basket,name='remove-order-detail-ajax'),
    path('remove_basket_card_order_detail/',views.remove_user_basket_card_order_detail,name='remove_user_basket_card_order_detail-ajax'),
    path('change_order_detail_count/',views.change_order_detail_count,name='change-order-detail-count-ajax'),
    path("apply-coupon/", views.apply_coupon, name="apply_coupon"),
    path('checkout/',views.CheckOutView.as_view(),name="user-checkout"),
    # path('checkout/',views.checkout,name="user-checkout"),


    # path('checkout/',views.UserCheckOutBasket.as_view(),name='order-checkout'),
    # path('coupon-apply/',views.CouponApplyView.as_view(),name='coupon-apply'),
    # path('remove_product_from_basket/<int:detail_id>/',views.remove_product_from_basket,name='remove-product-from-basket'),
    # path('remove_basket_cart/<int:detail_id>/',views.remove_basket_cart,name="remove-basket-cart"),
    # path('remove_product_from_basket_ajax/',views.remove_product_from_basket_ajax,name='remove-product-from-basket-ajax'),
    # path('confirm_checkout/',views.confirm_checkout,name='confirm-checkout'),
]

app/project/product_module/urls.py
from django.urls import path,re_path
from . import views


app_name="product_module"
urlpatterns = [
    # products 
    path('',views.ProductListView.as_view(),name='products'),
    # product detail
    path('<int:pk>/<slug:slug>/',views.ProductDetailView.as_view(),name='product-detail'),
    re_path(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/\Z$', views.ProductDetailView.as_view(), name='product-detail'),
    # add product to user fav list
    path('add-to-user-favorite-list/',views.add_remove_product_to_favorite_list,name='add-product-to-favorite-list'),
    path('add-product-comment/',views.add_product_comment,name="add-product-comment")
]

app/project/order_module/views.py
# import datetime
# from django.urls import reverse
# from django.template.loader import render_to_string
# from django.contrib import messages
# from permissions import is_authenticated_permission
# from .forms import CouponApplyForm
# from .models import Coupon
# from django.utils.timezone import now
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse,HttpResponse
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from product_module.models import Product
from site_settings_module.models import SiteSetting
from .models import OrderBasket,OrderDetail,Coupon
from .forms import CheckOutForm
from django.contrib import messages



def add_product_to_basket(request):
    if request.user.is_authenticated:
        
        product_id=int(request.GET.get('product_id'))
        count=int(request.GET.get('count')) #get method returns str
        if count<=0:
            return JsonResponse({
            'status':'not-invalid',
            'title':'alert',
            'text':'اطلاعات نامعتبر',
            'icon':'error',
            'confirm_button_text':'باشه'
        })

        product=Product.objects.filter(id=product_id,is_active=True,is_delete=False).first()

        if product is not None:
            current_order,is_created=OrderBasket.objects.get_or_create(is_paid=False,user_id=request.user.id)
            current_order_detail=current_order.order_detail.filter(product_id=product_id).first()
            if current_order_detail is not None:
                current_order_detail.count+=count
                current_order_detail.save()
            else:
                new_order_detail=OrderDetail(product_id=product_id,count=count,order_basket_id=current_order.id)
                new_order_detail.save()
                
            return JsonResponse({
                'status':'success',
                'title':'اعلان',
                'text':'محصول به سبد خرید شما با موفقیت اضافه شد',
                'icon':'success',
                'confirm_button_text':'باشه'
            })
        else:
            return JsonResponse({
                'status':'not-invalid',
                'title':'alert',
                'text':'اطلاعات نامعتبر',
                'icon':'error',
                'confirm_button_text':'باشه'
            })
    else:
        return JsonResponse({
            'status':'not-authenticated',
            'title':'هشدار',
            'text':'ابتدا باید وارد حساب خود شوید',
            'icon':'warning',
            'confirm_button_text':'رفتن به صفحه ورود'
        })


@method_decorator(login_required, name='dispatch')
class UserOrderBasket(View, LoginRequiredMixin):
    template_name = 'order_module/basket.html'

    def get(self, request):
        current_basket, _ = OrderBasket.objects.prefetch_related('order_detail').get_or_create(is_paid=False, user_id=request.user.id)

        return render(request, self.template_name, {
            'user_basket': current_basket,
            'need_for_free_transportation': SiteSetting.get_free_shipping_threshold(),
            'transportation_rate': SiteSetting.get_transportation_rate(),
        })

    
@login_required
def remove_user_basket_card_order_detail(request):
    detail_id = request.GET.get('detail_id')

    current_basket = OrderBasket.objects.prefetch_related('order_detail').filter(is_paid=False, user_id=request.user.id).first()
    # current_basket, _ = OrderBasket.objects.prefetch_related('order_detail').get_or_create(is_paid=False, user_id=request.user.id)
    
    if detail_id == "all":
        current_basket.order_detail.all().delete()
        
    elif detail_id is None:
        return JsonResponse({'status': 'detail-not-found'})
    else:
        count, _ = OrderDetail.objects.filter(
            id=detail_id, order_basket=current_basket
        ).delete()
        
        if count == 0:
            return JsonResponse({'status': 'detail-not-found'})
        
        # updated_basket = OrderBasket.objects.prefetch_related('order_detail').filter(is_paid=False, user_id=request.user.id).first()
        # updated_basket, _ = OrderBasket.objects.prefetch_related('order_detail').get_or_create(is_paid=False, user_id=request.user.id)
        current_basket.order_detail.set(current_basket.order_detail.exclude(id=detail_id))

    context = {
        'user_basket': current_basket,
        'need_for_free_transportation': SiteSetting.get_free_shipping_threshold(),
        'transportation_rate': SiteSetting.get_transportation_rate(),
    }

    return JsonResponse({
        'status': 'success',
        'body': render_to_string("order_module/includes/basket_cart.html", context),
        'mobile_body': render_to_string("order_module/includes/basket_cart_mobile.html", context),
        'mbody': render_to_string("order_module/includes/remove_order_detail_ajax.html", context),
    })


@login_required
def change_order_detail_count(request):
    detail_id = request.GET.get('detail_id')
    state = request.GET.get('state')

    if not detail_id or not state:
        return JsonResponse({'status': 'invalid-request'})

    target_order_detail = OrderDetail.objects.filter(
        order_basket__user_id=request.user.id, id=detail_id, order_basket__is_paid=False
    ).first()

    if not target_order_detail:
        return JsonResponse({'status': 'detail-not-found'})

    if state == "increase":
        target_order_detail.count += 1
        target_order_detail.save()
    elif state == "decrease":
        if target_order_detail.count == 1:
            target_order_detail.delete()
        else:
            target_order_detail.count -= 1
            target_order_detail.save()
    else:
        return JsonResponse({'status': 'invalid-state'})

    current_basket, _ = OrderBasket.objects.prefetch_related('order_detail').get_or_create(is_paid=False, user_id=request.user.id)

    context = {
        'user_basket': current_basket,
        'need_for_free_transportation': SiteSetting.get_free_shipping_threshold(),
        'transportation_rate': SiteSetting.get_transportation_rate(),
    }

    return JsonResponse({
        'status': 'success',
        'body': render_to_string("order_module/includes/remove_order_detail_ajax.html", context),
        'mobile_body': render_to_string("order_module/includes/basket_cart_mobile.html", context),

    })


@csrf_exempt
def apply_coupon(request):
    if request.method == "POST":
        coupon_code = request.POST.get("coupon_code", "").strip()

        if not coupon_code:
            return JsonResponse({"status": "error", "message": "کد تخفیف را وارد کنید!"})

        try:
            coupon = Coupon.objects.get(code=coupon_code)
        except Coupon.DoesNotExist:
            return JsonResponse({"status": "error", "message": "کد تخفیف نامعتبر است!"})

        if not coupon.is_valid():
            return JsonResponse({"status": "error", "message": "کد تخفیف منقضی شده است!"})

        # Get the user's basket
        basket = OrderBasket.objects.prefetch_related('order_detail').filter(user=request.user, is_paid=False).first()

        if not basket:
            return JsonResponse({"status": "error", "message": "سبد خریدی یافت نشد!"})

        # Apply coupon
        if basket.coupon and basket.coupon == coupon:
            return JsonResponse({"status": "error", "message": "کد تخفیف قبلا اعمال شده"})
        basket.coupon = coupon
        basket.save(update_fields=["coupon"])

        total_with_tr=float(basket.get_total_amount())+float(SiteSetting.get_transportation_rate())

        context = {
            'user_basket': basket,
            'need_for_free_transportation': SiteSetting.get_free_shipping_threshold(),
            'transportation_rate': SiteSetting.get_transportation_rate(),
            'total_with_tr':total_with_tr
            }

        return JsonResponse({
            "status": "success",
            "message": "کد تخفیف اعمال شد!",
            'body': render_to_string("order_module/includes/remove_order_detail_ajax.html", context),
            "new_total": basket.get_total_amount(),
        })

    return JsonResponse({"status": "error", "message": "درخواست نامعتبر است!"})


class CheckOutView(View,LoginRequiredMixin):
    template_name="order_module/checkout.html"
    form_class=CheckOutForm

    def get(self,request):
        user = request.user
        address = user.user_address.first()  # Get the first address if available
        user_order_basket=OrderBasket.objects.prefetch_related('order_detail').filter(is_paid=False, user_id=request.user.id).first()

        context={
            'form':self.form_class(instance=address, user=user),
            'order_basket':user_order_basket,
            'need_for_free_transportation': SiteSetting.get_free_shipping_threshold(),
            'transportation_rate': SiteSetting.get_transportation_rate(),
            'total':user_order_basket.get_total_amount() if user_order_basket.get_total_amount() > SiteSetting.get_free_shipping_threshold() else SiteSetting.get_free_shipping_threshold()+user_order_basket.get_total_amount(),
        }
        return render(request,self.template_name,context)

    # def post(self,request):
    #     user = request.user
    #     address = user.user_address.first() 
    #     user_order_basket=OrderBasket.objects.prefetch_related('order_detail').filter(is_paid=False, user_id=request.user.id).first()
    #     if not user_order_basket.order_detail:

app/project/order_module/templates/order_module/includes/basket_cart.html
{% load poll_extras %}


<div id="basket-card">
    {% if user_basket.order_detail.all %}
    <i class="fa-sharp fa-regular fa-cart-shopping" data-basket-count="{{user_basket.order_detail.count}}" ></i>
    <span class="text">سبد خرید من</span>
    <div class="category-sub-menu card-number-show">
        <h5 class="shopping-cart-number">سبد خرید ({{user_basket.order_detail.count}})</h5>
        {% for order in user_basket.order_detail.all %}
            <div class="cart-item-1 {% if forloop.first %}border-top{% endif %}">
                <div class="img-name">
                    <div class="thumbanil">
                        <img src="{{order.product.image.url}}" alt="" />
                    </div>
                    <div class="details">
                        <a href="shop-details.html">
                            <h5 class="title">{{order.product.title|truncatechars:80}}</h5>
                        </a>
                        <div class="number">
                            {{order.count}}
                            x
                            {% comment %} <i class="fa-regular fa-x"></i> {% endcomment %}

                            {% if order.product.price_with_discount %}
                                <span>{{order.product.price_with_discount|three_digits}} تومان</span>
                            {% else %}
                                <span>{{order.product.price|three_digits}} تومان</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="close-c1">
                    <a onclick="removeOrderBasket({{order.id}})"><i class="fa-regular fa-times"></i></a>
                </div>
            </div>
        {% endfor %}
        <div class="sub-total-cart-balance">
            <div class="bottom-content-deals mt--10">
                <div class="top">
                    <span>مجموع فرعی: </span>
                    <span class="number-c">{{user_basket.get_total_amount|three_digits}} تومان</span>
                </div>
                {% if user_basket.get_total_amount > need_for_free_transportation %}
                    <div class="single-progress-area-incard">
                        <div class="progress">
                            <div class="progress-bar wow fadeInRight" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <p><span></span> خرید شما بیشتر از {{need_for_free_transportation|three_digits}} هزار تومان میباشد.بنا براین میتوانید از گزینه ارسال رایگان استفاده کنید</p>
                {% else %}
                    <div class="single-progress-area-incard">
                        <div class="progress">
                            <div class="progress-bar wow fadeInRight" role="progressbar" style="width: {{user_basket.get_free_transportation_progress|safe}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <p><span> {{user_basket.get_free_transportation|three_digits}}تومان</span> به سبد خرید اضافه کنید و ارسال رایگان دریافت کنید</p>
                {% endif %}
            </div>
            <div class="button-wrapper d-flex align-items-center justify-content-between">
                <a href="{% url "order_module:order-basket" %}" class="rts-btn btn-primary">مشاهده سبد </a>
                <a href="{% url "order_module:user-checkout" %}" class="rts-btn btn-primary border-only">صفحه پرداخت</a>
            </div>
        </div>
    </div>
    <a href="{% url "order_module:order-basket" %}" class="over_link"></a>    
    {% else %}
    <i class="fa-sharp fa-regular fa-cart-shopping" data-basket-count="0"></i>
        <span class="text">سبد خرید من</span>
        <div class="category-sub-menu card-number-show">
            <h5 class="shopping-cart-number">سبد خرید (0)</h5>
            <div class="cart-item-1 border-top">
                <h2>سبد خرید شما خالی است</h2>
            </div>
            <div class="sub-total-cart-balance">
                <div class="bottom-content-deals mt--10">
                    <div class="top">
                        <span>مجموع فرعی: </span>
                        <span class="number-c">{{user_basket.get_total_amount|three_digits}} تومان</span>
                    </div>
                    {% if user_basket.get_total_amount > need_for_free_transportation %}
                        <div class="single-progress-area-incard">
                            <div class="progress">
                                <div class="progress-bar wow fadeInRight" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <p><span></span> خرید شما بیشتر از {{need_for_free_transportation|three_digits}} هزار تومان میباشد.بنا براین میتوانید از گزینه ارسال رایگان استفاده کنید</p>
                    {% else %}
                        <div class="single-progress-area-incard">
                            <div class="progress">
                                <div class="progress-bar wow fadeInRight" role="progressbar" style="width: {{user_basket.get_free_transportation_progress|safe}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <p><span> {{user_basket.get_free_transportation|three_digits}}تومان</span> به سبد خرید اضافه کنید و ارسال رایگان دریافت کنید</p>
                    {% endif %}
                </div>
                <div class="button-wrapper d-flex align-items-center justify-content-between">
                    <a href="{% url "order_module:order-basket" %}" class="rts-btn btn-primary">مشاهده سبد </a>
                </div>
            </div>
        </div>
        <a href="{% url "order_module:order-basket" %}" class="over_link"></a>
    {% endif %}
</div>

app/project/order_module/templates/order_module/includes/basket_cart_mobile.html
{% load poll_extras %}

<div id="basket-card-mobile">
    {% if user_basket.order_detail.all %}
    <i class="fa-sharp fa-regular fa-cart-shopping" data-basket-count="{{user_basket.order_detail.count}}" style="--basket-count:'{{user_basket.order_detail.count}}';" ></i>
    <span class="text">سبد خرید من</span>
    <div class="category-sub-menu card-number-show">
        <h5 class="shopping-cart-number">سبد خرید ({{user_basket.order_detail.count}})</h5>
        {% for order in user_basket.order_detail.all %}
            <div class="cart-item-1 {% if forloop.first %}border-top{% endif %}">
                <div class="img-name">
                    <div class="thumbanil">
                        <img src="{{order.product.image.url}}" alt="" />
                    </div>
                    <div class="details">
                        <a href="shop-details.html">
                            <h5 class="title">{{order.product.title|truncatechars:60}}</h5>
                        </a>
                        <div class="number">
                            {{order.count}}
                            <i class="fa-regular fa-x"></i>
                            {% if order.product.price_with_discount %}
                                <span>{{order.product.price_with_discount|three_digits}} تومان</span>
                            {% else %}
                                <span>{{order.product.price|three_digits}} تومان</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="close-c1">
                    <a onclick="removeOrderBasket({{order.id}})"><i class="fa-regular fa-x"></i></a>
                </div>
            </div>
        {% endfor %}
        <div class="sub-total-cart-balance">
            <div class="bottom-content-deals mt--10">
                <div class="top">
                    <span>مجموع فرعی: </span>
                    <span class="number-c">{{user_basket.get_total_amount}} تومان</span>
                </div>
                {% if user_basket.get_total_amount > need_for_free_transportation %}
                    <div class="single-progress-area-incard">
                        <div class="progress">
                            <div class="progress-bar wow fadeInRight" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <p><span></span> خرید شما بیشتر از {{need_for_free_transportation|three_digits}} هزار تومان میباشد.بنا براین میتوانید از گزینه ارسال رایگان استفاده کنید</p>
                {% else %}
                    <div class="single-progress-area-incard">
                        <div class="progress">
                            <div class="progress-bar wow fadeInRight" role="progressbar" style="width: {{user_basket.get_free_transportation_progress|safe}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <p> {{user_basket.get_free_transportation|three_digits}} تومان به سبد خرید اضافه کنید و ارسال رایگان دریافت کنید  </p>
                {% endif %}
            </div>
            <div class="button-wrapper d-flex align-items-center justify-content-between">
                <a href="{% url "order_module:order-basket" %}" class="rts-btn btn-primary">مشاهده سبد </a>
                <a href="{% url "order_module:user-checkout" %}" class="rts-btn btn-primary border-only">صفحه پرداخت</a>
            </div>
        </div>

    </div>
    <a href="{% url "order_module:order-basket" %}" class="over_link"></a>    
    {% else %}
        <i class="fa-sharp fa-regular fa-cart-shopping" data-basket-count="0" ></i>
        <span class="text">سبد خرید من</span>
        <div class="category-sub-menu card-number-show">
            <h5 class="shopping-cart-number">سبد خرید (0)</h5>
            <div class="cart-item-1 border-top">
                <h2>سبد خرید شما خالی است</h2>
            </div>
            <div class="sub-total-cart-balance">
                <div class="bottom-content-deals mt--10">
                    <div class="top">
                        <span>مجموع فرعی: </span>
                        <span class="number-c">0 تومان</span>
                    </div>
                    <div class="single-progress-area-incard">
                        <div class="progress">
                            <div class="progress-bar wow fadeInRight" role="progressbar" style="width: 0%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <p> {{user_basket.get_free_transportation|three_digits}} تومان به سبد خرید اضافه کنید و ارسال رایگان دریافت کنید  </p>
                </div>
                <div class="button-wrapper d-flex align-items-center justify-content-between">
                    <a href="{% url "product_module:products" %}" class="rts-btn btn-primary border-only">خرید</a>
                </div>
            </div>
        </div>
        <a href="{% url "order_module:order-basket" %}" class="over_link"></a>
    {% endif %}
</div>
















{% comment %} <i class="fa-sharp fa-regular fa-cart-shopping"></i>
<span>سبد خرید من</span>
<div class="category-sub-menu card-number-show">
    <h5 class="shopping-cart-number">سبد خرید (03)</h5>
    <div class="cart-item-1 border-top">
        <div class="img-name">
            <div class="thumbanil">
                <img src="/static/assets/images/shop/cart-1.png" alt="" />
            </div>
            <div class="details">
                <a href="shop-details.html">
                    <h5 class="title">مرغ به شکل ناگت سینه فاستر فاستر</h5>
                </a>
                <div class="number">
                    1<i class="fa-regular fa-x"></i>
                    <span>36.00 تومان</span>
                </div>
            </div>
        </div>
        <div class="close-c1">
            <i class="fa-regular fa-x"></i>
        </div>
    </div>
    <div class="sub-total-cart-balance">
        <div class="bottom-content-deals mt--10">
            <div class="top">
                <span>مجموع فرعی: </span>
                <span class="number-c">108.00 تومان</span>
            </div>
            <div class="single-progress-area-incard">
                <div class="progress">
                    <div class="progress-bar wow fadeInRight" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <p><span>125.00 تومان</span> بیشتر خرج کنید تا به <span>ارسال رایگان برسید</span></p>
        </div>
        <div class="button-wrapper d-flex align-items-center justify-content-between">
            <a href="cart.html" class="rts-btn btn-primary">مشاهده سبد </a>
            <a href="checkout.html" class="rts-btn btn-primary border-only">خرید</a>
        </div>
    </div>
</div>
<a href="cart.html" class="over_link"></a> {% endcomment %}