app/project/blog_module/urls.py
from django.urls import path,re_path
from . import views


app_name='blog_module'
urlpatterns = [
    path('',views.ArticleListView.as_view(),name="articles"),
    # article comment
    path('add-comment/article_comment/',views.add_article_comment,name='add-article-comment'),
    # article detail
    path('<int:pk>/<slug:slug>/',views.ArticleDetailView.as_view(),name="article-detail"),
    re_path(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/\Z$', views.ArticleDetailView.as_view(), name='article-detail'),
]

app/project/ghanbari_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_module.urls',namespace='home_module')),
    path('account/',include('account_module.urls',namespace='account_module')),
    path('contact-us/',include('contact_module.urls',namespace='contact_module')),
    path('about-us/',include('about_us_module.urls',namespace='about_us_module')),
    path('products/',include('product_module.urls',namespace='product_module')),
    path('orders/',include('order_module.urls',namespace='order_module')),
    path('blog/',include('blog_module.urls',namespace='blog_module')),
    path('profile/',include('user_profile_module.urls',namespace='user_profile_module')),
    path('ckeditor5/', include('django_ckeditor_5.urls')), 
    path('zarinpal/', include('zarinpal_module.urls',namespace='zarinpal_module')), 
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

app/project/product_module/urls.py
from django.urls import path,re_path
from . import views


app_name="product_module"
urlpatterns = [
    # products 
    path('',views.ProductListView.as_view(),name='products'),
    # product detail
    path('<int:pk>/<slug:slug>/',views.ProductDetailView.as_view(),name='product-detail'),
    re_path(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/\Z$', views.ProductDetailView.as_view(), name='product-detail'),
    # add product to user fav list
    path('add-to-user-favorite-list/',views.add_remove_product_to_favorite_list,name='add-product-to-favorite-list'),
    path('add-product-comment/',views.add_product_comment,name="add-product-comment")
]

app/project/product_module/forms.py
from django import forms
from .models import ProductCommentReview


class ProductFilterForm(forms.Form):
    PRODUCT_FILTERING_CHOICES = [
        ('all', 'همه محصولات'),
        ('discounted', 'محصولات تخفیف خورده'),
        # ('no-discount', 'محصولات بدون تخفیف'),
        ('most-bought', 'محصولات پرطرفدار'),
    ]
    product_filter = forms.ChoiceField(choices=PRODUCT_FILTERING_CHOICES,
                                        label='',
                                        required=False,
                                        widget=forms.Select(attrs={
                                            'name':"sort",
                                            'id':"sort",
                                            'onchange':"updateSorting()"
                                            }))
    # product_filter = forms.ChoiceField(choices=PRODUCT_FILTERING_CHOICES,label='',required=False, widget=forms.Select())


class ProductCommentReviewForm(forms.ModelForm):
    PRODUCT_RATING_CHOICES = [
        ('5', '5'),
        ('4', '4'),
        ('3', '3'),
        ('2', '2'),
        ('1', '1'),
    ]
    
    product_rating = forms.ChoiceField(
        choices=PRODUCT_RATING_CHOICES,
        label='',
        required=True,
        widget=forms.Select(attrs={
            'class': 'rating-dropdown',  # Add class for styling
            'name': "rating",
            'id': "rating",
        })
    )
    # description = forms.CharField(
    #     widget=forms.Textarea(attrs={
    #         'id':'description'
    #     })
    # )
    class Meta:
        model = ProductCommentReview
        fields = ["product_rating", "description"]




# class ProductCommentReviewForm(forms.Form):
#     PRODUCT_RATING_CHOICES = [
#         ('5', '5'),
#         ('4', '4'),
#         ('3', '3'),
#         ('2', '2'),
#         ('1', '1'),
#     ]
#     product_rating = forms.ChoiceField(choices=PRODUCT_RATING_CHOICES,
#                                         label='',
#                                         required=True,
#                                         widget=forms.Select(attrs={
#                                             'name':"product_rating",
#                                             'id':"product_rating",
#                                             }))
#     description=forms.CharField(widget=forms.Textarea(attrs={
#         'class':'form-control',
#         'placeholder':'متن پیام شما',
#         'rows':4,
#     }))


# class ProductCommentReviewForm(forms.ModelForm):
#     class Meta:
#         model = ProductCommentReview
#         fields = ["rating", "description"]
#         widgets = {
#             "rating": forms.Select(choices=[
#                 ('5', '5'),
#                 ('4', '4'),
#                 ('3', '3'),
#                 ('2', '2'),
#                 ('1', '1'),
#             ], attrs={'name': "rating", 'id': "rating"})
#         }



# class ProductCommentReviewForm(forms.ModelForm):
#     class Meta:
#         model = ProductCommentReview
#         fields = ["rating", "description"]  # Exclude user fields

#     def __init__(self, *args, **kwargs):
#         self.user = kwargs.pop('user', None)  # Get user from view
#         super().__init__(*args, **kwargs)

#         if self.user and self.user.is_authenticated:
#             self.fields['rating'].widget.attrs.update({'class': 'form-control'})  # Example styling

#     def save(self, commit=True):
#         instance = super().save(commit=False)
#         if self.user and self.user.is_authenticated:
#             instance.user = self.user  # Assign the logged-in user
#         if commit:
#             instance.save()
#         return instance

app/project/product_module/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView,DetailView, FormView
from django.db.models import Sum,Count
from django.db.models import Q
from django.http import JsonResponse,HttpResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from user_profile_module.models import UserFavoriteProduct
from account_module.models import User
from .models import Product,ProductImage, ProductCommentReview
from .forms import ProductFilterForm,ProductCommentReviewForm
from .models import Product, ProductCommentReview


class ProductListView(ListView):
    template_name="product_module/products.html"
    model=Product
    context_object_name='products'
    ordering=['-added_date']
    paginate_by=5


    def get_queryset(self):        
        query=super().get_queryset().filter(is_active=True)

        search_query = self.request.GET.get('product-search', '')
        product_filter = self.request.GET.get('product_filter')

        if search_query:
            query = query.filter(
                Q(title__icontains=search_query) |  # Search in title
                Q(short_description__icontains=search_query)  # Search in short_description
            )

        if product_filter == "discounted":
            query=query.filter(discount_percent__gte=1)

        elif product_filter == "no-discount":
            query=query.filter(discount_percent__lte=0)
            # query=query.filter(product__discount_percent__gte=1,is_active=True)

        elif product_filter == "most-bought":
            # query = query.annotate(buy_count=Count('orderitem')).order_by('-buy_count')
            query = query.annotate(
                total_sold=Sum('orderdetail__count', filter=Q(orderdetail__order_basket__is_paid=True))
            ).order_by('-total_sold')


        return query
    
    def get_context_data(self, **kwargs):
        '''
            if need to pass new data in product template and
            this is not product model must send with this method and override this
        '''
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['filter_form']=ProductFilterForm(self.request.GET or None)
        return context
    

class ProductDetailView(DetailView,FormView):
    template_name='product_module/product_detail.html'
    model=Product
    context_object_name='product'
    form_class=ProductCommentReviewForm

    def get_queryset(self):
        return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loaded_product=self.object
        
        # product images
        product_images=list(ProductImage.objects.filter(product_id=loaded_product.id).all())
        product_images.insert(0,loaded_product)
        context['product_images']=product_images

        # accepted product comments
        # context['avg_rate']=loaded_product.avg_rate,  # Pass average rating
        accepted_comments = ProductCommentReview.objects.filter(product=loaded_product, status=2).order_by('-created_date')
        context.update({
            "accepted_comments": accepted_comments,
            "avg_rate": loaded_product.avg_rate,
            # "form": self.form_class(),
            "form": self.get_form(),
        })

        return context
    
    def get_object(self, queryset = None):
        queryset=Product.objects.get(pk=self.kwargs['pk'],slug=self.kwargs['slug'])
        return queryset 

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs["user"] = self.request.user  # Pass the logged-in user to the form
    #     return kwargs
    
    # def form_valid(self, form):
    #     product = self.get_object()
    #     comment = form.save(commit=False)
    #     comment.product = product
    #     comment.user = self.request.user  # Assuming the user is logged in
    #     comment.save()
    #     return super().form_valid(form)
    
    # def get_success_url(self):
    #     return self.get_object().get_absolute_url()  # Reload product page

    # def get_success_url(self):
    #     return self.request.path  # Redirect to the same product detail page after form submission

    

    # def post(self, request, *args, **kwargs):
    #     print(request.POST)
    #     """Handle form submission."""
    #     self.object = self.get_object()  # Load product instance
    #     form = self.get_form()

    #     if form.is_valid():
    #         return self.form_valid(form)
    #     else:
    #         return self.form_invalid(form)


def add_remove_product_to_favorite_list(request):
    if request.user.is_authenticated:
        product_id=int(request.GET.get('product_id'))
        target_product=get_object_or_404(Product,id=product_id,is_active=True,is_delete=False)
        if target_product is not None:
            check_product=UserFavoriteProduct.objects.filter(product_id=product_id,user_id=request.user.id).first()
            if check_product is not None:
                check_product.delete()
                return JsonResponse({
                        'status':'success',
                        'title':'هشدار',
                        'text':'از لیست مورد علاقه ها حذف شد',
                        'icon':'success',
                        'confirm_button_text':'باشه',
                        'product_id':product_id,
                        'action':'removing'
                    })
            else:    
                add_product_to_favorites=UserFavoriteProduct(user_id=request.user.id,product_id=target_product.id)
                add_product_to_favorites.save()

                return JsonResponse({
                        'status':'success',
                        'title':'هشدار',
                        'text':'به لیست مورد علاقه ها اضافه شد',
                        'icon':'success',
                        'confirm_button_text':'باشه',
                        'product_id':product_id,
                        'action':'adding'
                    })
        
        else:
            return JsonResponse({
                'status':'invalid-product-id',
                'title':'خطا',
                'text':'اطلاعات نامعتبر',
                'icon':'error',
                'confirm_button_text':'باشه'
            })
    else:
        return JsonResponse({
            'status':'not-authenticated',
            'title':'هشدار',
            'text':'برای اضافه کردن محصول به لیست مورد علاقه های خود باتدا باید وارد حساب کاربری خود شوید',
            'icon':'error',
            'confirm_button_text':'ورود به حساب'
            })


def add_product_comment(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            product_id = request.POST.get('product_id')
            comment_text = request.POST.get('comment')
            product_rating = request.POST.get('product_rating')

            # Check if product exists
            if not Product.objects.filter(id=product_id).exists():
                return JsonResponse({'status': 'invalid-product',
                                     'icon':'error',
                                     'title':'خطا',
                                        'message': 'محصول پیدا نشد'})
            
            user=request.user.id
            check_user=User.objects.get(id=user)
            if not check_user:
                return JsonResponse({'status': 'user-not-found',
                                     'icon':'error',
                                     'title':'خطا',
                                        'message': 'حساب کاربری پیدا نشد'})
            
            # Create and save comment (assuming you have a user system)
            ProductCommentReview.objects.create(
                product_id=product_id,
                user=request.user,  # Assuming the user is authenticated
                description=comment_text,
                rating=product_rating,
                status="0"  # Assuming "0" means pending review
            )

            return JsonResponse({'status': 'success',
                                 'icon':'success',
                                  'message': 'نظر شما با موفقیت ثبت شد.پس از بررسی ادمین نظر شما به نظرات اضافه میشود'})

        return JsonResponse({'status': 'not-authenticated',
                             'icon':'warning',
                             'title':'هشدار',
                              'message': 'کاربر احراز هویت لازم دارد!'})
    return JsonResponse({'status': 'error',
                         'icon':'error',
                         'title':'خطا',
                          'message': 'درخواست نامعتبر!!'})



# class ProductDetailView(DetailView):
#     template_name='product_module/product_detail.html'
#     model=Product
#     context_object_name='product'
    
#     def get_queryset(self):
#         return super().get_queryset()
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         loaded_product=self.object
#         product_images=list(ProductImage.objects.filter(product_id=loaded_product.id).all())
#         product_images.insert(0,loaded_product)
#         context['product_images']=product_images
#         return context

#     def get_object(self, queryset = None):
#         queryset=Product.objects.get(pk=self.kwargs['pk'],slug=self.kwargs['slug'])
#         return queryset 

app/project/product_module/templates/product_module/includes/product_comments.html
<div class="comments-section">
    {% for comment in accepted_comments %}
        <div class="single-review">
            {% if comment.user.first_name or comment.user.last_name %}
                <h5 class="user-name">{{comment.user.first_name}} {{ comment.user.last_name }}</h5>
            {% elif comment.user.email %}
                <h5 class="user-name">{{comment.user.email}}</h5>
            {% else %}
                <h5 class="user-name">کاربر</h5>
            {% endif %}
            <div class="stars">
                {% for i in "12345" %}
                    <i class="fa {% if comment.rating >= forloop.counter %}fa-solid fa-star{% elif comment.rating > forloop.counter0 and comment.rating < forloop.counter %}fa-solid fa-star-half-alt{% else %}fa-regular fa-star{% endif %}"></i>
                {% endfor %}
            </div>
            <p class="comment-text">{{ comment.description }}</p>
            <br>
        </div>
    {% empty %}
        <p class="text-center">اولین نفری باشید که نظر خود را ثبت میکند</p>
    {% endfor %}
</div>

app/project/product_module/templates/product_module/includes/product_item.html
{% load thumbnail %}
{% load poll_extras %}


<div class="single-shopping-card-one">
    <!-- Image and action area start -->
    <div class="image-and-action-area-wrapper">
        <a href="{% url 'product_module:product-detail' pk=product.pk slug=product.slug %}" class="thumbnail-preview">
            {% if product.discount_percent %}
                <div class="badge">
                    <span>
                        {{ product.discount_percent }}%<br />
                        تخفیف
                    </span>
                    <i class="fa-solid fa-bookmark"></i>
                </div>
            {% endif %}
            {% thumbnail product.image "257x223" quality=100 crop="center" as im %}
                <img src="{{ im.url }}" alt="{{ product.title }}" />
            {% endthumbnail %}
        </a>
        <div class="action-share-option cursor-pointer">
            <a onclick="addProductToFavoriteList({{ product.id }})">
                <div class="single-action openuptip message-show-action" data-flow="up" title="افزودن به علاقمندی ها">
                    <i id="product_{{product.id}}" {% if product.id|is_favorite_product:request.user.id %}class="fa-light fa-heart favorite-heart" {% else %}class="fa-light fa-heart" {% endif %}>
                    </i>
                </div>
            </a> 
            <div 
                class="single-action openuptip cta-quickview product-details-popup-btn"
                data-flow="up"
                title="مشاهده سریع"
                data-product-id={{product.id}}
                data-product-weight={% if product.weight %}{{product.weight}}{% else %}""{% endif %}
                data-title="{{ product.title }}"
                data-image="{{ product.image.url }}"
                data-price="{{ product.price_with_discount }}"
                data-old-price="{{ product.price }}"
                data-description="{{ product.short_description }}"
                data-stock="{% if product.quantity > 0 %}موجود{% else %}ناموجود{% endif %}"
                data-rating="{{ product.rating }}"
                data-extra-images='[{% for img in product.images.all %}"{{ img.image.url }}"{% if not forloop.last %}, {% endif %}{% endfor %}]'
            >
                <i class="fa-regular fa-eye"></i>
            </div>
        </div>
    </div>
    <!-- Image and action area end -->

    <!-- Body content -->
    <div class="body-content">
        <a href="shop-details.html">
            <h4 class="title card-text">{{ product.title|truncatechars:40}}</h4>
        </a>
        {% if product.weight %}
            <span class="availability">بسته {{ product.weight }} گرمی</span>
        {% endif %}
        <div class="price-area">
            {% if product.price_with_discount %}
                <span class="current price-style">{{ product.price_with_discount }} تومان</span>
                <div class="previous">{{ product.price }} تومان</div>
                {% else %}
                <div class="current price-style">{{ product.price }} تومان</div>
            {% endif %}
        </div>
        <div class="cart-counter-action">
            <div class="quantity-edit">
                <input id="productCount_{{product.id}}" type="text" min="1" class="input" value="1"/>
                <div class="button-wrapper-action">
                    <button class="button"><i class="fa-regular fa-chevron-down"></i></button>
                    <button class="button plus">+<i class="fa-regular fa-chevron-up"></i></button>
                </div>
            </div>
            
            <a onclick="addProductToBasket({{product.id}})" class="rts-btn radious-sm with-icon cursor-pointer">
                <div class="btn-text">
                    اضافه کردن
                </div>
                <div class="arrow-icon">
                    <i class="fa-regular fa-cart-shopping"></i>
                </div>
            </a>
        </div>
    </div>
    <!-- Body content end -->
</div>







{% comment %} 
    <div class="single-shopping-card-one card">
        <!-- Image and action area start -->
        <div class="image-and-action-area-wrapper">
            <a href="{% url 'product_module:product-detail' pk=product.pk slug=product.slug %}" class="thumbnail-preview">
                {% if product.discount_percent %}
                    <div class="badge">
                        <span>
                            {{ product.discount_percent }}%<br />
                            تخفیف
                        </span>
                        <i class="fa-solid fa-bookmark"></i>
                    </div>
                {% endif %}
                {% thumbnail product.image "257x223" quality=85 crop=center as im %}
                    <img src="{{ im.url }}" alt="{{ product.title }}" />
                {% endthumbnail %}
            </a>
            <div class="action-share-option cursor-pointer">
                <a onclick="addProductToFavoriteList({{ product.id }})">
                    <div class="single-action openuptip message-show-action" data-flow="up" title="افزودن به علاقمندی ها">
                        <i id="product_{{product.id}}" {% if product.id|is_favorite_product:request.user.id %}class="fa-light fa-heart favorite-heart" {% else %}class="fa-light fa-heart" {% endif %}>
                        </i>
                    </div>
                </a> 
                <div 
                    class="single-action openuptip cta-quickview product-details-popup-btn"
                    data-flow="up"
                    title="مشاهده سریع"
                    data-title="{{ product.title }}"
                    data-image="{{ product.image.url }}"
                    data-price="{{ product.price_with_discount }}"
                    data-old-price="{{ product.price }}"
                    data-description="{{ product.short_description }}"
                    data-stock="{% if product.quantity > 0 %}موجود{% else %}ناموجود{% endif %}"
                    data-rating="{{ product.rating }}"
                    data-extra-images='[{% for img in product.images.all %}"{{ img.image.url }}"{% if not forloop.last %}, {% endif %}{% endfor %}]'
                >
                    <i class="fa-regular fa-eye"></i>
                </div>
            </div>
        </div>
        <!-- Image and action area end -->

        <!-- Body content -->
        <div class="body-content">
            <a href="shop-details.html">
                <h4 class="title card-text">{{ product.title }}</h4> <!-- Title inside card-text -->
            </a>
            <span class="availability">بسته {{ product.weight }} گرمی</span>
            <div class="price-area">
                <span class="current">{{ product.price_with_discount }} تومان</span>
                <div class="previous">{{ product.price }} تومان</div>
            </div>
            <div class="cart-counter-action">
                <div class="quantity-edit">
                    <input id="productCount_{{product.id}}" type="text" min="1" class="input" value="1"/>
                    <div class="button-wrapper-action">
                        <button class="button"><i class="fa-regular fa-chevron-down"></i></button>
                        <button class="button plus">+<i class="fa-regular fa-chevron-up"></i></button>
                    </div>
                </div>
                
                <a onclick="addProductToBasket({{product.id}})" class="rts-btn btn-primary radious-sm with-icon cursor-pointer">
                    <div class="btn-text">
                        اضافه کردن
                    </div>
                    <div class="arrow-icon">
                        <i class="fa-regular fa-cart-shopping"></i>
                    </div>
                </a>
            </div>
        </div>
        <!-- Body content end -->
    </div> 
{% endcomment %}

app/project/product_module/templates/product_module/includes/product_modal.html
{% load poll_extras %}


<!-- modal -->
    <div class="product-details-popup-wrapper">
        <div class="rts-product-details-section rts-product-details-section2 product-details-popup-section">
            <div class="product-details-popup">
                <button class="product-details-close-btn"><i class="fal fa-times"></i></button>
                <div class="details-product-area">
                    <div class="product-thumb-area">
                        <div class="cursor"></div>
                        <div class="thumb-wrapper one filterd-items figure">
                            <div class="product-thumb zoom" onmousemove="zoom(event)" style="background-image: url();">
                                <img src="" alt="" />
                            </div>
                        </div>
                        {% comment %} <div class="product-thumb-filter-group">
                            <div class="thumb-filter filter-btn active" data-show=".one"><img src="" alt="" /></div>
                        </div> {% endcomment %}
                    </div>
                    <div class="contents">
                        <div class="product-status">
                            <div class="rating-stars-group">
                                <div class="rating-star"><i class="fas fa-star"></i></div>
                                <span>10 بررسی</span>
                            </div>
                        </div>
                        <h2 class="product-title"> <span class="stock"></span></h2>
                        <span class="product-price">
                            <span class="old-price">9.35</span> 
                            7.25 تومان</span>
                        <p>
                            
                        </p>
                        <div class="product-bottom-action">
                            <div class="cart-edit">
                                <div class="quantity-edit action-item">
                                    <button class="button"><i class="fal fa-minus minus"></i></button>
                                    <input id="modalProductCount" type="text" min="1" class="input" value="1"/>
                                    <button class="button plus">+<i class="fal fa-plus plus"></i></button>
                                </div>
                            </div>
                            <a onclick="addModalProductToBasket()" class="rts-btn radious-sm with-icon cursor-pointer add-to-basket-btn">
                                <div class="btn-text">
                                    اضافه کردن
                                </div>
                                <div class="arrow-icon">
                                    <i class="fa-regular fa-cart-shopping"></i>
                                </div>
                            </a>
                            {% comment %} <a href="javascript:void(0);" class="rts-btn btn-primary ml--20"><i class="fa-light fa-heart"></i></a> {% endcomment %}
                        </div>
                        <div class="product-uniques">
                            <span class="sku product-unipue mb--10"><span class="product-id" style="font-weight: 400; margin-left: 10px;">شناسه محصول:</span> </span>
                            <span class="sku product-unipue mb--10"><span class="product-weight" style="font-weight: 400; margin-left: 10px;">وزن محصول:</span> </span>
                            <span class="sku product-unipue mb--10"><span class="stock">موجودی</span></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- end modal -->